name: energy-forecast
channels: 

 - conda-forge
 - defaults

dependencies:
 - python=3.11
 - pandas
 - numpy
 - matplotlib
 - scikit-learn
 - statsmodels
 - pmdarima
 - prophet
 - jupyterlab
 - ipykernel
 - pip

 
     
 - pip:
      - holidays
